
spring:
  application:
    name: android-web
  datasource:
    url: jdbc:mysql://8.131.250.250:3306/mhk?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: mhk
    password: 001008ma
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8081

