
spring:
  datasource:
    url: jdbc:mysql://db.yynb.live:33066/mhk?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: ltl
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8081

