name: Docker Build And Push To Aliyun Hub

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build Spring Boot
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout Code
        uses: actions/checkout@v1
        id: git_checkout

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build with Maven
        run: mvn -B  package --file pom.xml -Dmaven.test.skip=true

      - name: Push Docker
        run: |
          docker login --username=${{ secrets.USERNAME }} --password ${{ secrets.PASSWORD }} registry.cn-qingdao.aliyuncs.com
          docker build . -t ${{ secrets.REGISTRY }}:v1.0.0
          docker push ${{ secrets.REGISTRY }}:v1.0.0
          docker tag $(docker images ${{ secrets.REGISTRY }}:v1.0.0 -q) ${{ secrets.REGISTRY }}:latest
          docker push ${{ secrets.REGISTRY }}:latest


