name: JAVA Continuous Deployment

on:
  push:
    branches: [ master ]
    paths:
      - src/**
      - pom.xml
      - Dockerfile
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: 编译&构建Docker镜像
    timeout-minutes: 6
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout Code
        uses: actions/checkout@v1
        id: git_checkout

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build with Maven
        run: mvn -B  package --file pom.xml -Dmaven.test.skip=true

      - name: Publish to Docker Hub
        uses: LucienShui/Publish-Docker-Github-Action@2.7.1
        with:
          name: ${{ secrets.DOCKER_IMAGE_NAME }} # docker image 的名字
          username: ${{ secrets.ALIYUN_USERNAME }} # 用户名
          password: ${{ secrets.ALIYUN_PASSWORD }} # 密码
          registry: ${{ secrets.DOCKER_IMAGE_REGISTRY }} # Docker Hub 地址
          dockerfile: Dockerfile # 指定 Dockerfile 的位置
          tag_names: true # 是否将 release 的 tag 作为 docker image 的 tag
  
  pull-docker:
    needs: [build]
    name: 服务器启动Docker
    timeout-minutes: 6
    runs-on: ubuntu-latest
    steps:
      - name: Pull and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            docker stop $(docker ps --filter ancestor=${{ secrets.DOCKER_IMAGE_NAME }}:latest -q)
            docker rm -f $(docker ps -a --filter ancestor=${{ secrets.DOCKER_IMAGE_NAME }}:latest -q)
            docker rmi -f $(docker images  ${{ secrets.DOCKER_IMAGE_NAME }}:latest -q)
            docker login --username=${{ secrets.ALIYUN_USERNAME }} --password ${{ secrets.ALIYUN_PASSWORD }} ${{ secrets.DOCKER_IMAGE_REGISTRY }}
            docker pull ${{ secrets.DOCKER_IMAGE_NAME }}:latest
            docker run -d -p ${{ secrets.DOCKER_PUBLIC_PORT }}:${{ secrets.DOCKER_APP_PORT }} ${{ secrets.DOCKER_IMAGE_NAME }}:latest
            
